# basic infomation
DIMENSION 10 6
FPS 2
FRAMES 9
IGNORE '~'


# frame num start from 0
# blank frame
START 0
END

FRAME 1
+--------+
|~~~~~~~~|
|~~~~~~~~|
|~~~~~~~~|
|~~~~~~~~|
+--------+
END

FRAME 2
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~n~~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 3
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~g~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 4
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~~u~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 5
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~ ~~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 6
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~ ~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 7
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~~ ~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 8
END
