DEF_SCENE opening
DEF_SCENE body
DEF_SCENE closing
# -----------------------------

MOD_SCENE opening
DIMENSION 10 6
FPS 1
FRAMES 1
IGNORE = '~'

FRAME 0
HIHIHIHIHIHIHIHI
END

DONE_MOD

# -----------------------------
MOD_SCENE body
DIMENSION 10 6
FPS 2
FRAMES 7
IGNORE '~'

FRAME 0
+--------+
|~~~~~~~~|
|~~~~~~~~|
|~~~~~~~~|
|~~~~~~~~|
+--------+
END

FRAME 1
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~n~~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 2
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~g~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 3
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~~u~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 4
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~ ~~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 5
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~ ~~~~~
~~~~~~~~~~
~~~~~~~~~~
END

FRAME 6
~~~~~~~~~~
~~~~~~~~~~
~~~~~~~~~~
~~~~~ ~~~~
~~~~~~~~~~
~~~~~~~~~~
END

DONE_MOD
# ---------------------------------------

MOD_SCENE closing
DIMENSION 10 6
FPS 1
FRAMES 1
IGNORE '~'

FRAME 0
----------
----------
----BYE---
----------
----------
----------
END

DONE_MOD
# --------------------------------------------

INSTRUCTION
PLAY opening
REP body 3
PLAY closing
END
